version: '3.8'

services:
  mysql-full-text-search:
    image: mysql:8.0.27
    container_name: mysql-full-text-search
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - 'dbdata:/var/lib/mysql'

volumes:
    dbdata: {}